application.name = Markdown Table Editor
application.version = ${project.version}
markdown.file = markdown file
button.reload = Reload
button.save = Save
button.load = Load
button.filter = Filter
font.size = Font Size
menu.file = File
menu.column = Column
menu.row = Row
menu.edit = Edit
menu.view = View
menu.close = Close
menu.rename = Rename / Align
menu.insert = Insert
menu.delete = Delete
menu.undo = Undo
menu.redo = Redo
menu.copy = Copy
menu.cut = Cut
menu.paste = Paste
menu.replace = Replace
menu.filter = Filter
find.what = Find What: 
replace.with = Replace With:
search = Search
replace = Replace
backward = Backward
replace.all = Replace All
rename.column = Properties of the Column
textfield.size = 40
add.column = Direction to add a column
left = Left
center = Center
right = Right
upper = Upper
lower = Lower
cancel = Cancel
ok = OK
search.not = Excluding
row = Row
column = Column